/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.gui.spidtimain;

import java.awt.Cursor;
import java.io.File;
import user.gui.tools.IconGetter;

/**
 *Barracuda loader is intended to be the main launcher frame for other UI's
 * @author
 * <p>
 * Diego Garibay-Pulido 2016</p>
 */
public class BarracudaLoader extends javax.swing.JFrame {
    private static File file;

    /**
     * Creates new form BarracudaLoader
     */
    public BarracudaLoader() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainIcon = new javax.swing.JLabel();
        barracudaViewButton = new javax.swing.JButton();
        pspiDTIDialogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(IconGetter.getProjectIcon("brain128.png")
        );

        mainIcon.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mainIcon.setForeground(new java.awt.Color(0, 102, 153));
        mainIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Capture.png"))); // NOI18N

        barracudaViewButton.setText("Barracuda View");
        barracudaViewButton.setToolTipText("");
        barracudaViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barracudaViewButtonActionPerformed(evt);
            }
        });

        pspiDTIDialogButton.setText("pspiDTI");
        pspiDTIDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pspiDTIDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barracudaViewButton)
                        .addGap(18, 18, 18)
                        .addComponent(pspiDTIDialogButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(mainIcon)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barracudaViewButton)
                    .addComponent(pspiDTIDialogButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barracudaViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barracudaViewButtonActionPerformed
        launchViewer(this);
    }//GEN-LAST:event_barracudaViewButtonActionPerformed

    private void pspiDTIDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pspiDTIDialogButtonActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));  
        (new Thread(new pspiDTIRunnable(this))).start();     
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pspiDTIDialogButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarracudaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarracudaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarracudaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarracudaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        BarracudaLoader a= new BarracudaLoader();
        java.awt.EventQueue.invokeLater(() -> {
            a.setVisible(true);
        });
        
        try{
            String filename=args[0];
            if(filename!=null){
                (new Thread(() -> {
                    a.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                    BarracudaViewUI b= new BarracudaViewUI(filename);
                    b.setVisible(true);
                    b.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                            b.dispose();
                            Thread.currentThread().interrupt();
                            a.setVisible(true);
                        }
                    });
                    a.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    a.setVisible(false);
                })).start();
                
            }
        }catch(ArrayIndexOutOfBoundsException e){
            
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barracudaViewButton;
    private javax.swing.JLabel mainIcon;
    private javax.swing.JButton pspiDTIDialogButton;
    // End of variables declaration//GEN-END:variables
    private static void launchViewer(BarracudaLoader a){
        ViewerRunnable runnable=new ViewerRunnable(a);
        file=runnable.getFile();
        Thread thr= new Thread(runnable);
        thr.start();
    }
    
    
}
