/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.gui.spidtimain;
import data.niftilibrary.niftijio.*;
import java.io.IOException;
import java.io.File;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.*;
import user.gui.tools.UITools;
//import javax.jnlp.*;

/**
 *  <p>This is the main class for the pspiDTI UI it includes the menus and
 * a NIFTI file viewer.</p>  
 * 
 * @author Diego Garibay-Pulido 2016
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    NiftiVolume niiVol;
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddFileBtn = new javax.swing.JButton();
        coronalPanel = new javax.swing.JPanel();
        coronalLabel1 = new javax.swing.JLabel();
        coronalLabel = new javax.swing.JLabel();
        coronalLabel3 = new javax.swing.JLabel();
        coronalLabel2 = new javax.swing.JLabel();
        coronalLabel4 = new javax.swing.JLabel();
        coronalSlider = new javax.swing.JSlider();
        axialPanel = new javax.swing.JPanel();
        axialLabel1 = new javax.swing.JLabel();
        axialLabel = new javax.swing.JLabel();
        axialLabel2 = new javax.swing.JLabel();
        axialLabel3 = new javax.swing.JLabel();
        axialLabel4 = new javax.swing.JLabel();
        axialSlider = new javax.swing.JSlider();
        saggitalPanel = new javax.swing.JPanel();
        saggitalLabel = new javax.swing.JLabel();
        saggitalLabel3 = new javax.swing.JLabel();
        saggitalLabel2 = new javax.swing.JLabel();
        saggitalLabel4 = new javax.swing.JLabel();
        saggitalLabel5 = new javax.swing.JLabel();
        saggitalSlider = new javax.swing.JSlider();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barracuda View");
        setIconImage(getMainIcon());

        AddFileBtn.setText("Open Nifti");
        AddFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFileBtnActionPerformed(evt);
            }
        });

        coronalLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coronalLabel1.setText("L");
        coronalLabel1.setToolTipText("");

        coronalLabel.setBackground(new java.awt.Color(0, 0, 0));
        coronalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coronalLabel.setToolTipText("");

        coronalLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coronalLabel3.setText("R");

        coronalLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coronalLabel2.setText("S");
        coronalLabel2.setToolTipText("");

        coronalLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        coronalLabel4.setText("I");
        coronalLabel4.setToolTipText("");

        coronalSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                coronalSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout coronalPanelLayout = new javax.swing.GroupLayout(coronalPanel);
        coronalPanel.setLayout(coronalPanelLayout);
        coronalPanelLayout.setHorizontalGroup(
            coronalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coronalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coronalLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(coronalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(coronalSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coronalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coronalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coronalLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(coronalLabel3)
                .addGap(13, 13, 13))
        );
        coronalPanelLayout.setVerticalGroup(
            coronalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coronalPanelLayout.createSequentialGroup()
                .addComponent(coronalSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coronalLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coronalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(coronalLabel1)
                    .addComponent(coronalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coronalLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coronalLabel4)
                .addGap(15, 15, 15))
        );

        axialPanel.setPreferredSize(new java.awt.Dimension(579, 560));
        axialPanel.setRequestFocusEnabled(false);

        axialLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        axialLabel1.setText("L");

        axialLabel.setBackground(new java.awt.Color(0, 0, 0));
        axialLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        axialLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        axialLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        axialLabel2.setText("A");
        axialLabel2.setToolTipText("");

        axialLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        axialLabel3.setText("R");

        axialLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        axialLabel4.setText("P");

        axialSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                axialSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout axialPanelLayout = new javax.swing.GroupLayout(axialPanel);
        axialPanel.setLayout(axialPanelLayout);
        axialPanelLayout.setHorizontalGroup(
            axialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(axialPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(axialLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(axialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(axialSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(axialLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(axialLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(axialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(axialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        axialPanelLayout.setVerticalGroup(
            axialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(axialPanelLayout.createSequentialGroup()
                .addComponent(axialLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(axialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(axialLabel1)
                    .addComponent(axialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(axialLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(axialLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(axialSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        saggitalPanel.setPreferredSize(new java.awt.Dimension(569, 552));

        saggitalLabel.setBackground(new java.awt.Color(0, 0, 0));
        saggitalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saggitalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        saggitalLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saggitalLabel3.setText("A");

        saggitalLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saggitalLabel2.setText("P");
        saggitalLabel2.setToolTipText("");

        saggitalLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saggitalLabel4.setText("S");
        saggitalLabel4.setToolTipText("");

        saggitalLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saggitalLabel5.setText("I");
        saggitalLabel5.setToolTipText("");

        saggitalSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                saggitalSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout saggitalPanelLayout = new javax.swing.GroupLayout(saggitalPanel);
        saggitalPanel.setLayout(saggitalPanelLayout);
        saggitalPanelLayout.setHorizontalGroup(
            saggitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saggitalPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(saggitalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(saggitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(saggitalSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saggitalLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saggitalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saggitalLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(saggitalLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        saggitalPanelLayout.setVerticalGroup(
            saggitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saggitalPanelLayout.createSequentialGroup()
                .addComponent(saggitalSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saggitalLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saggitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(saggitalLabel2)
                    .addComponent(saggitalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saggitalLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saggitalLabel5)
                .addGap(15, 15, 15))
        );

        panel1.setBackground(new java.awt.Color(240, 240, 240));

        jLabel1.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddFileBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(coronalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(axialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saggitalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddFileBtn)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saggitalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coronalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(axialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))))
        );

        AddFileBtn.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFileBtnActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(MainUI.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String filename = file.getAbsolutePath();
            
            System.out.println(filename);
            try{
                niiVol= NiftiVolume.read(filename);
                Map map=niiVol.header.info();
                System.out.println(map);
                BufferedImage b = null;
                b =niiVol.drawNiftiSlice((int)(niiVol.header.dim[1]/2), "saggital", 0);
                UITools.imageToLabel(b,saggitalLabel);
                b =niiVol.drawNiftiSlice((int)(niiVol.header.dim[2]/2), "coronal", 0);
                UITools.imageToLabel(b,coronalLabel);
                b =niiVol.drawNiftiSlice((int)(niiVol.header.dim[3]/2), "axial", 0);
                UITools.imageToLabel(b,axialLabel);
                
                saggitalSlider.setMaximum(niiVol.header.dim[1]-1);
                saggitalSlider.setValue((int)(niiVol.header.dim[1]/2));
                coronalSlider.setMaximum(niiVol.header.dim[2]-1);
                coronalSlider.setValue((int)(niiVol.header.dim[2]/2));
                axialSlider.setMaximum(niiVol.header.dim[3]-1);
                axialSlider.setValue((int)(niiVol.header.dim[3]/2));
            }
            catch (IOException e){
                System.err.println("error: " + e.getMessage());
            }
        } else {
            returnVal=0;
        }
            
    }//GEN-LAST:event_AddFileBtnActionPerformed

    private void coronalSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_coronalSliderStateChanged
        if(niiVol!=null){
            BufferedImage b = niiVol.drawNiftiSlice((int)coronalSlider.getValue(),"coronal",0);
            UITools.imageToLabel(b,coronalLabel);
        }
        
    }//GEN-LAST:event_coronalSliderStateChanged

    private void saggitalSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_saggitalSliderStateChanged
        if(niiVol!=null){
             BufferedImage b = niiVol.drawNiftiSlice((int)saggitalSlider.getValue(),"saggital",0);
             UITools.imageToLabel(b,saggitalLabel);
        }
    }//GEN-LAST:event_saggitalSliderStateChanged

    private void axialSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_axialSliderStateChanged
         if(niiVol!=null){
            BufferedImage b =niiVol.drawNiftiSlice((int)axialSlider.getValue(),"axial",0);
            UITools.imageToLabel(b,axialLabel);
        }
    }//GEN-LAST:event_axialSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFileBtn;
    private javax.swing.JLabel axialLabel;
    private javax.swing.JLabel axialLabel1;
    private javax.swing.JLabel axialLabel2;
    private javax.swing.JLabel axialLabel3;
    private javax.swing.JLabel axialLabel4;
    private javax.swing.JPanel axialPanel;
    private javax.swing.JSlider axialSlider;
    private javax.swing.JLabel coronalLabel;
    private javax.swing.JLabel coronalLabel1;
    private javax.swing.JLabel coronalLabel2;
    private javax.swing.JLabel coronalLabel3;
    private javax.swing.JLabel coronalLabel4;
    private javax.swing.JPanel coronalPanel;
    private javax.swing.JSlider coronalSlider;
    private javax.swing.JLabel jLabel1;
    private java.awt.Panel panel1;
    private javax.swing.JLabel saggitalLabel;
    private javax.swing.JLabel saggitalLabel2;
    private javax.swing.JLabel saggitalLabel3;
    private javax.swing.JLabel saggitalLabel4;
    private javax.swing.JLabel saggitalLabel5;
    private javax.swing.JPanel saggitalPanel;
    private javax.swing.JSlider saggitalSlider;
    // End of variables declaration//GEN-END:variables
private Image getMainIcon(){
    Image img= null;
    try {
        img=ImageIO.read(new File("images/synapticom2.png"));
        setIconImage(img);
    }
    catch (IOException exc) {
        exc.printStackTrace();
    }
    return img;
}
}

