/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.gui.spidtimain;

import data.niftilibrary.niftijio.DrawableNiftiVolume;
import java.awt.GridLayout;
import javax.swing.JLabel;
import user.gui.tools.*;

/**
 *
 * @author
 * <p>
 * Diego Garibay-Pulido 2016</p>
 */
public class MosaicViewFrame extends javax.swing.JFrame {
    DrawableNiftiVolume niiVol;
    DrawableNiftiVolume overlayVol;
    boolean view;
    /**
     * Creates new form MosaicViewFrame
     */
    public MosaicViewFrame(DrawableNiftiVolume niiVol ,DrawableNiftiVolume overlayVol,boolean view,int[] grid) {
        initComponents();
        this.niiVol=niiVol;
        this.overlayVol=overlayVol;
        this.view=view;
        initMosaic(grid[0],grid[1]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mosaicToolbar = new javax.swing.JToolBar();
        coronalMosaicViewButton = new javax.swing.JButton();
        saggitalMosaicViewButton = new javax.swing.JButton();
        axialMosaicViewButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        mosaicToolbar.setFloatable(false);
        mosaicToolbar.setRollover(true);

        coronalMosaicViewButton.setText("C");
        coronalMosaicViewButton.setToolTipText("Coronal View");
        coronalMosaicViewButton.setFocusable(false);
        coronalMosaicViewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coronalMosaicViewButton.setMaximumSize(new java.awt.Dimension(26, 26));
        coronalMosaicViewButton.setMinimumSize(new java.awt.Dimension(26, 26));
        coronalMosaicViewButton.setPreferredSize(new java.awt.Dimension(26, 26));
        coronalMosaicViewButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        coronalMosaicViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coronalMosaicViewButtonActionPerformed(evt);
            }
        });
        mosaicToolbar.add(coronalMosaicViewButton);

        saggitalMosaicViewButton.setText("S");
        saggitalMosaicViewButton.setToolTipText("Saggital View");
        saggitalMosaicViewButton.setFocusable(false);
        saggitalMosaicViewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saggitalMosaicViewButton.setMaximumSize(new java.awt.Dimension(26, 26));
        saggitalMosaicViewButton.setMinimumSize(new java.awt.Dimension(26, 26));
        saggitalMosaicViewButton.setPreferredSize(new java.awt.Dimension(26, 26));
        saggitalMosaicViewButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saggitalMosaicViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saggitalMosaicViewButtonActionPerformed(evt);
            }
        });
        mosaicToolbar.add(saggitalMosaicViewButton);

        axialMosaicViewButton.setText("A");
        axialMosaicViewButton.setToolTipText("Axial View");
        axialMosaicViewButton.setFocusable(false);
        axialMosaicViewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        axialMosaicViewButton.setMaximumSize(new java.awt.Dimension(26, 26));
        axialMosaicViewButton.setMinimumSize(new java.awt.Dimension(26, 26));
        axialMosaicViewButton.setName(""); // NOI18N
        axialMosaicViewButton.setPreferredSize(new java.awt.Dimension(26, 26));
        axialMosaicViewButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mosaicToolbar.add(axialMosaicViewButton);

        settingsButton.setIcon(IconGetter.getProjectImageIcon("settings_icon.png")
        );
        settingsButton.setToolTipText("Settings");
        settingsButton.setFocusable(false);
        settingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        settingsButton.setMaximumSize(new java.awt.Dimension(26, 26));
        settingsButton.setMinimumSize(new java.awt.Dimension(26, 26));
        settingsButton.setPreferredSize(new java.awt.Dimension(26, 26));
        settingsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        mosaicToolbar.add(settingsButton);

        displayPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mosaicToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mosaicToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coronalMosaicViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coronalMosaicViewButtonActionPerformed
        /*JLabel label1= new JLabel();
        displayPanel.add(label1);
        label1.setText("Hi");*/
        createTilePanel();
    }//GEN-LAST:event_coronalMosaicViewButtonActionPerformed

    private void saggitalMosaicViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saggitalMosaicViewButtonActionPerformed
        
    }//GEN-LAST:event_saggitalMosaicViewButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        
    }//GEN-LAST:event_settingsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton axialMosaicViewButton;
    private javax.swing.JButton coronalMosaicViewButton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JToolBar mosaicToolbar;
    private javax.swing.JButton saggitalMosaicViewButton;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
    
    private void initMosaic(int n,int m){
        GridLayout panelLayout = new GridLayout(n,m);
        displayPanel.setLayout(panelLayout);
    }
    /****Draw Slices****/
    private void drawCoronalSlice (int sliceNum){
        
    }
    private void drawSaggitalSlice(int sliceNum){
        
    }
    private void drawAxialSlice   (int sliceNum){
        
    }
    /****Draw Mosaics****/
    private void drawCoronalMosaic (int n, int m, int startSlice, int endSlice){
        
    }
    private void drawSaggitalMosaic(int n, int m, int startSlice, int endSlice){
        
    }
    private void drawAxialMosaic   (int n, int m, int startSlice, int endSlice){
        
    }
    /***Create Tile Panels***/
    private void createTilePanel(){
        displayPanel.setVisible(false);
        javax.swing.JPanel tilePanel = new javax.swing.JPanel();
        javax.swing.JLabel leftLabel = new javax.swing.JLabel();
        javax.swing.JLabel topLabel = new javax.swing.JLabel();
        javax.swing.JLabel rightLabel = new javax.swing.JLabel();
        javax.swing.JLabel bottomLabel = new javax.swing.JLabel();
        javax.swing.JLabel graphLabel = new javax.swing.JLabel();
        
        tilePanel.setBackground(new java.awt.Color(0, 0, 0));
        tilePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tilePanel.setPreferredSize(new java.awt.Dimension(150, 158));

        leftLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftLabel.setText("<html> <font size='3' color=\"Lime\"> R</font>");

        topLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLabel.setText("<html> <font size='3' color=\"Lime\"> R</font>");

        rightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightLabel.setText("<html> <font size='3' color=\"Lime\"> R</font>");

        bottomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bottomLabel.setText("<html> <font size='3' color=\"Lime\"> R</font>");

        javax.swing.GroupLayout tilePanelLayout = new javax.swing.GroupLayout(tilePanel);
        tilePanel.setLayout(tilePanelLayout);
        tilePanelLayout.setHorizontalGroup(
            tilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(tilePanelLayout.createSequentialGroup()
                .addComponent(leftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tilePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(tilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tilePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graphLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(rightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tilePanelLayout.setVerticalGroup(
            tilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilePanelLayout.createSequentialGroup()
                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(tilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(leftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graphLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(bottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        displayPanel.add(tilePanel);
        displayPanel.setVisible(true);
    }
}
